-- Subscriptions master table
create table if not exists public.subscriptions (
    id bigint primary key generated by default as identity,
    name text not null,
    price_monthly numeric,
    price_yearly numeric,
    max_tables integer,
    max_menu_items integer,
    max_admins integer,
    allow_custom_domain boolean,
    allow_qr_download boolean,
    allow_theme_customization boolean,
    allow_analytics boolean,
    allow_online_orders boolean,
    features jsonb,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
